---
name: File-Ignore
version: 0.021
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
abstract: Ignore files that are good to ignore
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0
build_requires:
  Test::Lazy: 0
  Test::More: 0
provides:
  File::Ignore:
    file: lib/File/Ignore.pm
    version: 0.021
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
